project:
  type: website

website:
  title: "Swe stats 1.0"
  navbar:
    background: primary
    right:
      - href: about.qmd
        text: Om Swe stats
      - icon: github
        href: https://github.com/tomasrei
  sidebar: 
    style: "docked"
    search: false
    contents: 
      - section: "Svensk arbetsmarknad"
        contents:
          - index.qmd


format:
  html:
    theme: yeti
    css: styles.css



